---
title: "Facebook’s Mark Zuckerberg Criticized for Free Speech Stance"
date: "2019-10-18"
categories: 
  - "aim-investigates"
---

In a jarring turn of events, civil rights leaders [criticized](https://www.nbcnews.com/news/nbcblk/civil-rights-leaders-rebuke-zuckerberg-s-free-speech-address-n1068461) social media platform giant Facebook and its CEO Mark Zuckerberg for its free speech policy changes. In a speech at Georgetown University, Zuckerberg said his company respects the freedom of speech and that it is not up to Facebook to censor content due to political or social views. Censorship could ultimately kill social movements and this policy could help “build a more inclusive society.”

Zuckerberg cited civil rights leaders, such as Martin Luther King, Jr. and ex-slave and abolitionist Frederick Douglass as examples of free speech, lack of censorship, and building a social movement. He compared these two historical figures to the “Me Too” and “Black Lives Matter” movements, which first began online on platforms such as Facebook.

But his speech was met with derision by King’s lone surviving daughter, Bernice King, and a prominent Black Lives Matter activist Alicia Garza. King blasted Zuckerberg for invoking her father’s name in his speech and said, “I heard #MarkZuckerberg's ‘free expression’ speech, in which he referenced my father. I'd like to help Facebook better understand the challenges #MLK faced from disinformation campaigns launched by politicians. These campaigns created an atmosphere for his assassination.”

Garza’s condemnation was markedly different, claiming that Facebook’s policy could enable or empower white supremacists in social media and online platforms. She tweeted her criticisms on the platform of Facebook’s social media competitor, Twitter. She said the following:

“If #BlackLivesMatter to Mark Zuckerberg, then he should ensure that Black users are not targeted with misinformation, harassment and censorship on his platform and stop cozying up to anti-Black forces. Until then, his company will be remembered as an enabler of white supremacy.”

In another tweet, Garza said, “It really lacks integrity for Mark Zuckerberg to even invoke @Blklivesmatter in this kind of insidious way. Not interested in being your mule. You’re being deceptive + it needs to stop.”

NBC News seemingly took Garza’s side, describing the Black Lives Matter movement and repercussions from its formation, “Garza and others in the Black Lives Matter movement have been threatened, described repeatedly on social media platforms and conservative TV outlets as violent and subjected to what Garza has described as surprise FBI visits.” NBC’s inserted an opinion which differed from reality, where Black Lives Matter activists [shouted down](http://accuracy-in-media.local:59986/on-target-blog/bill-clinton-wasnt-pleased-about-shouting-black-lives-matter-protesters/) former president Bill Clinton, [vandalized](http://accuracy-in-media.local:59986/on-target-blog/why-did-cbs-news-not-cover-black-lives-matter-vandalism-at-trumps-dc-hotel/) private property, rioted in Baltimore, Md. and [incurred](http://accuracy-in-media.local:59986/on-target-blog/remember-this-previous-black-lives-matter-riots-cost-baltimore-up-to-20-million-ferguson-5-7-million/) significant damages, and whose rhetoric allegedly [inspired](http://accuracy-in-media.local:59986/on-target-blog/abc-news-story-on-dallas-mother-wounded-in-shielding-her-kids-omits-black-lives-matter-motivation-of-shooter/) a gunmen to kill four Dallas, Texas, police officers.

Although King and Garza may have good intentions on calling out Zuckerberg and Facebook’s free speech policy, it may not be up to private or public companies to monitor free speech as it is a protected right under the First Amendment of the U.S. Constitution. Hate speech, for example, is protected by the First Amendment. Other companies have monitored and censored speech deemed to be hateful or offensive, and that is their prerogative. It is a tricky situation, and Facebook could be in it for pollical campaign dollars as NBC News suggested, but free speech is ultimately a freedom protected by the Constitution regardless of what views are espoused.
