---
title: "Issues Surround Study that Claims ‘Disinformation Still Running Rampant on Facebook’"
date: "2019-11-07"
categories: 
  - "aim-column"
---

The Columbia Journalism Review (CJR) [published](https://www.cjr.org/the_media_today/disinformation-facebook.php) an article citing a study about Facebook, which concluded that Facebook is permitting disinformation to run “rampant” on its social media platform. The study was conducted by [Avaaz](https://secure.avaaz.org/page/en/about/), which CJR said is “a site that specializes in raising public awareness about global public-policy issues.”

The study claimed that between January-October 2019, “politically relevant disinformation” reached over 158 million views, “enough to reach every reported registered vote in the US at least once.” The study used a top 100 content list from a Facebook-owned tool “that tracks the network’s most popular pages and links.”

Avaaz’s study claimed that more than 90 percent of the fake news stories on Facebook were negative and that “the majority of those were about Democrats or liberals.” The study claimed that fake news benefitted Republicans and conservatives because coverage of issues relevant to Republicans and conservatives were portrayed in a positive light.

However, Avaaz did not make the study public. Instead, the media and other interested parties must rely on a single source: progressive journalist Judd Legum. Legum has been known on Twitter to espouse liberal and progressive ideology, such as calling President Trump “racist” and that his rhetoric is “ugly,” among his many social media posts.

CJR, CNN’s [Brian Stelter](https://twitter.com/brianstelter/status/1192151521720446980), and countless other media outlets and pundits do not have another source outside of Legum, whose political ideology is well-known and calls into question Legum’s legitimacy as a neutral source of information and Avaaz’s political ideology or goals.

Also, the media’s reporting on the study is flawed because the media should not have to rely on a single source for reporting stories. There are countless examples of the mainstream media apologizing for poorly-sourced scoops from a single source and it fell into the trap of believing the scoop and information without being able to verify the scoop and information.

Upon further investigation, Avaaz could be considered a site that raises public awareness on public policy issues across the world, but it is far more than that. On its “About Us” site, Avaaz highlighted how it is a community-focused campaign, but is planning on affecting the global community. Many of its campaigns are progressive-focused, on issues such as climate change, and the site claims that it is a no-frills organization.

Another red flag is that Avaaz did not mention that it is a foundation on its site, but in its financial reports, it calls itself the “Avaaz Foundation.” It appears to try to hide its true purpose, despite the paragraphs-long information on its “About Us” [page](https://secure.avaaz.org/page/en/about/). To its credit, Avaaz included a decades’ worth of financial reports about the site, but the financial reports illustrate how Avaaz is far from a neutral community-based public policy awareness site. The site [received](https://avaazimages.avaaz.org/AVAAZ_2017_FORM_990_Public_Disclosure_Copy.pdf) over $19 million in contributions in 2017 and grants and spent under $4 million on salaries, compensation and benefits for its employees. For a community organization, and one that focuses on global issues, it is quite a wealthy organization.

There are significant red flags surrounding Avaaz’s study on Facebook’s alleged permissive fake news environment, such as Avaaz’s goals and mission, its funding sources, and why it outsourced the study to a single progressive online personality. The mainstream media has to do a better job of verifying the study’s information before running with the story.
