---
title: "Iran and Human Rights"
date: "2010-06-14"
categories: 
  - "briefing"
---

The human rights violations and overall human rights conditions in Iran have greatly deteriorated, guest panelists in the Heritage Foundation forum, “Human Rights Under Attack: Oppression in Iran,” claimed.

With Heritage Foundation Senior Fellow **Jim Phillips**, the three guest panelists discussed and agreed on the need for more U.S. government-led pressure for sanctions against **Iran**. Panelist **Renee Redman**, director of the Iran Human Rights Documentation Center, dissected the success of the Iranian government in “suppress[ing] dissent” of political dissidents. She said that the Iranian government has “successfully kept [suppression of dissent] off the newswaves” and has “targeted activists of all stripes, women’s activists, student activists…religious activists.”

As another part of the government’s “post-election crackdown” from last June, “churches have been shut down…[there have been] at least eight politically motivated executions since January 1st.” She stated she couldn’t “confirm [reports of] 88 executions” of political dissidents in the same time frame. For those who have been interrogated and accused of political dissidence, Redman outlined their three options: go inactive, go to prison, or leave the country.

Even then they are hardly home free. Upon release from prison, for example, “activists find they are unable to secure a job” due to government intervention of informing employers of the job applicants’ political leanings. Also, the authorities manage to keep prisoners incarcerated by increasing bail money “set in hundreds of dollars,” expensive for the average family there. Claiming that national security is at stake, alleges Redman, the Iranian government uses “[this] cover to go after [activists]” as if it were “settling old scores.”

The primary fear among Iranians, Redman points out, is “torture…and rape” during interrogations of imprisoned activists. The fear is widespread to the extent that families of these activists encourage their loved ones to leave the country. Among members of the group Committee of Human Rights Reporters “either all…are in prison or have left the country” because “they have been accused [of being] members” of a treasonous organization. “Because these penalties are much more dire,” argued Redman, “people have felt the need to leave immediately.”

According to **Golnaz Esfandiari**, a senior correspondent for Radio Liberty Europe, Iran “has never been a champion of human rights” but of “censorship.” She argued that “Iran’s human rights situation has gotten worse” since last year’s June elections. Esfandiari alleged it is worse because the Iranian government has created a “disruption of communications” within the nation to discourage communication between activists.

Also, the grandson of the founder of the Islamic Republic of Iran is currently “deprived of the right to speak to the public…just because he sided with the opposition leader” in the June elections. On the anniversary of the creation of the republic, when the grandson attempted to speak, he was promptly removed from the podium. Esfandiari alleged that in a coordinated effort, the audience “chanted ‘death to Moussavi’ [Iranian [opposition leader](http://www.academia.org/iranian-preconditions/)]” and the current Supreme Leader of Iran spoke without referring to the removal incident.

Esfandiari confirmed that “at least 72 people have been killed [in the] post-election crackdown.” When the panel was asked as to how many student demonstrators were killed after the June elections, Redman responded, “there is no good number.” Esfandiari could only confirm “at least five” but mentioned multiple internet videos of Iranian police crackdowns on students that resulted in multiple deaths. She acknowledged “Iran feels like a big prison these days.”

A new medium of communication for Iranian dissidents is Facebook in conjunction with YouTube, as student protesters use their cell phone cameras for recording purposes. “The difference,” Esfandiari said, “between political prisoners and others is that the political prisoners are moving from bigger prisons to smaller prisons.” However, the Iranian government’s “campaign of intimidation” has only strengthened the movement’s resolve with increased pressure. Another part of the “campaign of intimidation” is that “many students have been filmed protesting, [then they’ve] been banned from studying for two semesters.”

The Iranian opposition “has prepared itself for a long fight…named…the year of resistance,” which means “it’s going to be a long fight.” Citing a prominent imprisoned student activist, Esfandiari noted that the “tyranny cannot hide its real face forever. It will eventually retreat.”
