---
title: "Blurred Lines between Journalists and Activists"
date: "2014-08-26"
categories: 
  - "on-target-blog"
  - "accuracy-in-media"
  - "activism"
  - "al-sharpton"
  - "ferguson"
  - "huffington-post"
  - "journalism"
  - "michael-brown"
  - "msnbc"
  - "native-americans"
  - "ryan-j-reilly"
  - "washington-redskins"
---

While there have long been different types of journalists—most notably reporters whose job it is to report the facts and stories in a fair and balanced way, and opinion journalists, who are still supposed to be fact-based, yet their job is to express their opinion, and, in essence, make a case for something—what is relatively new is the activist journalist. These are people who participate in rallies or protests, or some other form of demonstration, and then use a platform—very often some form of new or social media—to advocate their positions. The latter have been very prominent during the last couple of weeks in Ferguson, Missouri.

Many of these activists have been on the front lines in Ferguson, and were quick to praise themselves as heroes and brave journalists.

Rick Reilly of The Huffington Post was one of the more notable cases, and even live-tweeted his arrest. Police aggression and militarization issues aside, Reilly went on MSNBC after his arrest and, possibly in his mind, became the center of attention. In one of the most embarrassing tweets in journalistic history, he tweeted a photo of what he thought were rubber bullets:

Rubber earplugs are commonly used at gun ranges and the like, further displaying Reilly's inexperience and naivety. Let's just say that conservatives on Twitter had a field day. Here is one example of a mocking tweet:

Al Sharpton, host and political commentator on his own weeknight show on MSNBC, went to Ferguson along with various national media outlets and their camera crews. The only news surrounding Sharpton was his impending visit to Missouri. MSNBC jumped on the Ferguson coverage bandwagon and saw their ratings plummet. But, there was no public reprimand of Sharpton from MSNBC after he went to Ferguson and made speeches that could have ignited further race riots. In fact, Sharpton, a race-huckster for many years, is considered a star on that network, who often visits the set of other MSNBC shows, and is treated as some kind of civil rights hero and a person of integrity. We went through this with him during the Trayvon Martin case. As Howie Kurtz, formerly with The Washington Post and CNN, now the host of Fox News' Media Buzz, said the other day, Sharpton is entitled to be an activist, and he's entitled to be the host of his own cable show, but MSNBC shouldn't allow him to be both. And it wasn't only Fox News that took exception.

LZ Granderson, an openly-gay, black reporter for CNN and ESPN, called Sharpton and other race agitators like him "charlatans" and called them a disgrace. He compared the situation to the bungled Duke men's lacrosse case, where innocent young white men had their lives forever tainted by false accusations from a young black woman seeking publicity.

Activism among liberal journalists has spread to the sports world. Journalists, their editorial boards and even American football commentators have now refrained from using the name of a prominent NFL team, the Washington Redskins. The Washington Post's editorial board recently said it would no longer use the name of the franchise, instead calling it "the Washington football team." Yet, they will still continue to use the logo in reporting. The board said, "While we wait for the National Football League to catch up with thoughtful opinion and common decency, we have decided that, except when it is essential for clarity or effect, we will no longer use the slur ourselves."

The paper has joined other newspapers and journalists in refusing to use the "offensive" nickname. At least one of the Post's sports columnists, Mike Wise, along with a plethora of other journalists like ESPN's Bomani Jones and Sports Illustrated's Peter King, refuses to use the name. Peter King has gone so far as to say that the nickname will be gone by 2016, adding to the commonly-used refrain of "wrong side of history," (as The Washington Post editorial board had said), which seems far from objective.

The majority of Redskins fans disagrees with these journalists, at least that's what a poll conducted last May indicated. 71% of fans said they oppose the name change, which solidifies the team owner's position that they will not change the name. Prominent football players and figures have lined up on opposite sides of the debate. Former Redskins players like Chris Cooley, Mark Moseley and former Chicago Bears head coach Mike Ditka call the name a source of pride. Ditka called the issue "so stupid it's appalling." He also said, "You have a right to do that, but to change the name, that's ridiculous. Change the Constitution—we've got people trying to do that, too, and they're doing a pretty good job" and blamed "all the politically correct idiots in America." Others, like former Redskins player London Fletcher and former NFL referee Mike Carey, were not comfortable with the name.

The Redskins, led by owner Dan Snyder, started a foundation to spearhead efforts to help Native Americans in the U.S. The Native American culture is one rife with alcoholism, unemployment and poverty—issues that have been ignored in the name controversy. An International Business Times piece in 2012 demonstrated the devastating effects of alcoholism among tribes, which is arguably far more dangerous for Native Americans than a name. A reservation highlighted in the piece, Pine Ridge, has 80% unemployment and half of their residents living below the poverty line, while the national average for Americans is 15.1%.

This move to change the team name has echoes of previous liberal efforts to force change, such as judges overruling pro-traditional marriage laws in several U.S. states. The silencing of the opposition is quite telling, with sides already demarcated and the journalists lining up on one side, versus an unrepresented (and sometimes majority of) Americans on the other.